#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

$schema: http://json-schema.org/draft-04/schema#
id: https://kroxylicious.io/schema/kms/AwsKmsConfig.yaml
description: The AWS KMS configuration schema
type: object
$javaType: Config
required:
  - endpointUrl
  - accessKey
  - secretKey
  - region
properties:
  endpointUrl:
    type: string
    format: uri
  accessKey:
    $ref: "https://schema.kroxylicious.io/io.kroxylicious.proxy.config.secret/PasswordProvider#"
  secretKey:
    $ref: "https://schema.kroxylicious.io/io.kroxylicious.proxy.config.secret/PasswordProvider#"
  region:
    description: AWS region
    type: string
  tls:
    $ref: "https://schema.kroxylicious.io/io.kroxylicious.proxy.config.tls/Tls#"