apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-proxy-1
resources:
  - 00.Namespace.my-proxy.yaml
  - 01.KafkaProxy.simple.yaml
  - 02.KafkaProxyIngress-cluster-ip.yaml
  - 03.KafkaService.my-cluster.yaml
  - 04.VirtualKafkaCluster.my-cluster.yaml
#transformers:
#  - transformer.yaml
#replacements:
#  - source:
#      kind: KafkaProxy
#      group: kroxylicious.io
#      version: v1alpha1
#      fieldPath: metadata.name
#    targets:
#      - select:
#          group: kroxylicious.io
#          kind: KafkaProxyIngress
#          version: v1alpha1
#        fieldPaths:
#          - spec/proxyRef/name
configurations:
  - name-references.yaml
