#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

$schema: http://json-schema.org/draft-04/schema#
id: https://schema.kroxylicious.io/io.kroxylicious.proxy.config.tls/Tls
description: Common TLS configuration
type: object
properties:
  key:
    type: object
    properties:
      privateKeyFile:
        description: location of a file containing the private key.
        type: string
      certificateFile:
        description: location of a file containing the certificate and intermediates.
        type: string
      storeFile:
        description: location of a key store, or reference to a PEM file containing both private-key and certificate/intermediates.
        type: string
      storePassword:
        $ref: "https://schema.kroxylicious.io/io.kroxylicious.proxy.config.secret/PasswordProvider#"
      keyPassword:
        $ref: "https://schema.kroxylicious.io/io.kroxylicious.proxy.config.secret/PasswordProvider#"
      storeType:
        description: |
          specifies the server key type.
          Legal values are those types supported by the platform {@link java.security.KeyStore},
          and PEM (for X-509 certificates express in PEM format).
        type: string
    oneOf:
      - required:
          - privateKeyFile
          - certificateFile
        not:
          properties:
            storeFile:
              additionalProperties: true
      - required:
          - storeFile
        not:
          properties:
            privateKeyFile:
              additionalProperties: true
            certificateFile:
              additionalProperties: true
  trust:
    type: object
