#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

$schema: http://json-schema.org/draft-04/schema#
id: https://schema.kroxylicious.io/io.kroxylicious.proxy.config.secret/PasswordProvider
description: Common specification of a password
type: object
properties:
  password:
    description: DEPRECATED. The password.
    type: string
  filePath:
    description: A file path pointing to a UTF-8 encoded file containing the password
    type: string
# The properties are mutually exclusive.
minProperties: 1
maxProperties: 1